Areas/Admin/Models/Participant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Prototype.Areas.Admin.Models
{
    public class Participant
    {   
        
        public int ParticipantId { get; set; }
        [Required]
        [EmailAddress]
        public string Participant_Email { get; set; }
        
        public int Participant_Phase { get; set; }

        public string Participant_Group { get; set; }
        

        public string  Participant_Gender { get; set; }
        
        public int Participant_Age { get; set; }

        public string Participant_ResponseId { get; set; }
    }




}

Areas/Admin/Controllers/ParticipantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Prototype.Areas.Admin.Models;
using Prototype.Areas.Identity.Data;
using Prototype.Models;

namespace Prototype.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ParticipantController : Controller

    {
        private readonly PrototypeContext _context;

        public ParticipantController(PrototypeContext context)
        {
            _context = context;
        }
        // GET: Participant

        public async Task<IActionResult> ListUsers(int? phase)
        {
            ViewData["Title"] = "Viewing All Participants";

            var participants = from m in _context.Participant
                               select m;
            if(phase == 1)
            {
                ViewData["Title"] = "Viewing All P1 Participants";
                participants = participants.Where(s => s.Participant_Phase == 1);
            }

            else if(phase == 2)
            {
                ViewData["Title"] = "Viewing All P2 Participants";
                participants = participants.Where(s => s.Participant_Phase == 2);
            }
            else if(phase == 3)
            {
                ViewData["Title"] = "Viewing All P2-A Participants";
                participants = participants.Where(s => s.Participant_Phase == 2 && s.Participant_Group == "A");
            }
            else if(phase == 4)
            {
                ViewData["Title"] = "Viewing All P2-B Participants";
                participants = participants.Where(s => s.Participant_Phase == 2 && s.Participant_Group == "B");
            }

            return View(await participants.ToListAsync());
        }
        
        public async Task <IActionResult> ListP1Users()
        {
            return RedirectToAction("ListUsers", new { phase = 1 });
        }

        public async Task<IActionResult> ListP2Users()
        {
            return RedirectToAction("ListUsers", new { phase = 2 });
        }

        public async Task<IActionResult> ListP2AUsers()
        {
            return RedirectToAction("ListUsers", new { phase = 3 });
        }

        public async Task<IActionResult> ListP2BUsers()
        {
            return RedirectToAction("ListUsers", new { phase = 4 });
        }


        public async Task<IActionResult> ListP2Usersz()
        {
            var participants = from m in _context.Participant
                               select m;

            participants = participants.Where(s => s.Participant_Phase == 2);

            return View("ListUsers", await participants.ToListAsync());
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: Participant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant
                .FirstOrDefaultAsync(m => m.ParticipantId == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // GET: Participant/Create
        
        public IActionResult Create()
        {
            return View();
        }

        // POST: Participant/Create
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(ListUsers));
            }
            catch
            {
                return View();
            }
        }

        // GET: Participant/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant
                .FirstOrDefaultAsync(m => m.ParticipantId == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participant/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Participant participant)
        {
            if (id != participant.ParticipantId)
            {
                return NotFound();
            }
            var participant2 = await _context.Participant.FindAsync(id);

            if (ModelState.IsValid)
            {
                participant2.Participant_Email = participant.Participant_Email;
                participant2.Participant_Group = participant.Participant_Group;
                participant2.Participant_Phase = participant.Participant_Phase;
                participant2.Participant_ResponseId = participant.Participant_ResponseId;

                try
                {
                    _context.Update(participant2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipantExists(participant.ParticipantId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));

            }
            return View(participant2);
        }
        // GET: Participant/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participant
                .FirstOrDefaultAsync(m => m.ParticipantId == id);
            if(participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _context.Participant.FindAsync(id);
            

            try
            {
                _context.Participant.Remove(participant);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private bool ParticipantExists(int id)
        {
                return _context.Participant.Any(e => e.ParticipantId == id);
        }
    }
}

Areas/Admin/Views/Participant/Delete.cshtml
@model Prototype.Areas.Admin.Models.Participant

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Participant Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Participant_Email)
        </dd>
        <dt class="col-sm-2">
            Participant Phase
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Participant_Phase)
        </dd>
        <dt class="col-sm-2">
            Participant Group
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Participant_Group)
        </dd>
        <dt class="col-sm-2">
            Participant ResponseID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Participant_ResponseId)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ParticipantId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/Participant/Details.cshtml
@model Prototype.Areas.Admin.Models.Participant

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout.cshtml";
}

    <h1>Details</h1>

    <div>
        <h4>Movie</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                Participant Email
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Participant_Email)
            </dd>
            <dt class="col-sm-2">
                Participant Phase
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Participant_Phase)
            </dd>
            <dt class="col-sm-2">
                Participant Group
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Participant_Group)
            </dd>
            <dt class="col-sm-2">
                Participant ResponseID
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Participant_ResponseId)
            </dd>
        </dl>

        <div>
            <a asp-action="Edit" asp-route-id="@Model.ParticipantId">Edit</a> |
            <a asp-action="Index">Back to List</a>
        </div>
        

    </div>

Areas/Admin/Views/Participant/Edit.cshtml
@model Prototype.Areas.Admin.Models.Participant

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ParticipantId" />
            <div class="form-group">
                <label asp-for="Participant_Email" class="control-label">Participant Email</label>
                <input asp-for="Participant_Email" class="form-control" />
                <span asp-validation-for="Participant_Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Participant_Phase" class="control-label">Participant Phase</label>
                <input asp-for="Participant_Phase" class="form-control" />
                <span asp-validation-for="Participant_Phase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Participant_Group" class="control-label">Participant Group</label>
                <input asp-for="Participant_Group" class="form-control" />
                <span asp-validation-for="Participant_Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Participant_ResponseId" class="control-label">Participant ResponseId</label>
                <input asp-for="Participant_ResponseId" class="form-control" />
                <span asp-validation-for="Participant_ResponseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/Participant/Index.cshtml
@{
    Layout = "_Layout.cshtml";

}

Areas/Admin/Views/Participant/ListUsers.cshtml
@model IEnumerable< Prototype.Areas.Admin.Models.Participant>
@{
    
    Layout = "_Layout.cshtml";

}


    <h2>@ViewData["Title"]</h2>

<p>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Participant Email
            </th>

            <th>
                Participant Phase
            </th>

            <th>
                Participant Group
            </th>

            <th>
                Participant ResponseID
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Participant_Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Participant_Phase)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Participant_Group)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Participant_ResponseId)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ParticipantId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ParticipantId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ParticipantId">Delete</a>
                    </td>
                </tr>
            }

        }
        else
        {
        <tr>
          <td>
             Nothing Found!
            </td>
        </tr>
                
        }

    </tbody>
    </table>
<a asp-action="Index">Back to List</a>

Areas/Admin/Views/Participant/_Layout.cshtml
@{

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}




<div>
    <a asp-controller="Participant" asp-action="ListUsers" class=" btn btn-danger"> View All Participants</a>
    <a asp-controller="Participant" asp-action="ListP1Users" class=" btn btn-danger"> View P1 Participants</a>
    <a asp-controller="Participant" asp-action="ListP2Users" class=" btn btn-danger"> View P2 Participants</a>
    <a asp-controller="Participant" asp-action="ListP2AUsers" class=" btn btn-danger"> View Phase 2 A</a>
    <a asp-controller="Participant" asp-action="ListP2BUsers" class=" btn btn-danger"> View Phase 2 B</a>
</div>
<div>
    @RenderBody()
</div>