Models/SiteData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Prototype.Models
{
    public class SiteData
    {

        public int SiteDataId { get; set; }

        public string SiteData_Link { get; set; }

        public string SiteData_Name { get; set; }

        public bool SiteData_Active { get; set; } = false;

        public int SiteData_Phase { get; set; }


    }
}

Areas/Admin/Controllers/SiteDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.EntityFrameworkCore;
using Prototype.Migrations;
using Prototype.Models;


namespace Prototype.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SiteDataController : Controller
    {

        private readonly PrototypeContext _context;

        public SiteDataController(PrototypeContext context)
        {
            
            _context = context;
  

        }
        // GET: SiteData

        public async Task<IActionResult> Index()
        {

            var SiteData = from s in _context.SiteData
                           select s;


            return View(await SiteData.ToListAsync());
        }
        // GET: SiteData/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SiteData/Create
        public ActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> ChangePhase()
        {
            var SiteData = from s in _context.SiteData
                           select s;
            
            return View(await SiteData.ToListAsync());

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task ChangePhaseFalse()
        {
            var SiteData2 = from s in _context.SiteData
                            select s;

            SiteData2 = SiteData2.Where(s => s.SiteData_Active == true);

            if (SiteData2 == null)
            {
                return;
            }

            foreach (var item in SiteData2)
            {
                item.SiteData_Active = false;
            }

            try
            {
                _context.UpdateRange(SiteData2);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SiteDataExits(SiteData2))
                {
                    return;
                }
                else
                {
                    throw;
                }
            }
            return;
           

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePhase(int id)
        {
            var sitedata = await _context.SiteData.FindAsync(id);

            if (sitedata == null)
            {
                return NotFound();
            }
            await ChangePhaseFalse();
            sitedata.SiteData_Active = true;

            try
            {
                _context.Update(sitedata);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                
                if (!SiteDataExits(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToAction(nameof(ChangePhase));
        }
        

        // POST: SiteData/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SiteData/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var SiteData = await _context.SiteData.FindAsync(id);

            if(SiteData ==null)
            {
                return NotFound();
            }

            return View(SiteData);
        }

        // POST: SiteData/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,[Bind("SiteDataId", "SiteData_Name","SiteData_Link")]SiteData sitedata)
        {
            if (id != sitedata.SiteDataId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var OldSiteData = await _context.SiteData.FindAsync(id);

                OldSiteData.SiteData_Link = sitedata.SiteData_Link;
                OldSiteData.SiteData_Name = sitedata.SiteData_Name;
                try
                {
                    // TODO: Add update logic here
                    _context.Update(OldSiteData);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SiteDataExits(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                };
                
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: SiteData/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SiteData/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private bool SiteDataExits(int id)
        {
            return _context.SiteData.Any(e => e.SiteDataId == id);
        }

        private bool SiteDataExits(IEnumerable<SiteData> sitedata)
        {
            foreach (var item in sitedata)
            {
                return _context.SiteData.Any(e => e.SiteDataId == item.SiteDataId);
            }

            return false;
        }
    }
}

Areas/Admin/Views/SiteData/ChangePhase.cshtml
@model IEnumerable<Prototype.Models.SiteData>
@{

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<link href="~/css/toggle.css" rel="stylesheet" />
<h2>Modify Site Content</h2>
@foreach (var active in Model)
{
    @if (active.SiteData_Active == true)
    {
        @await Html.PartialAsync("_ActivePage", active)
    }
}
<h3></h3>
<br>
<form asp-action="ChangePhase" method="post">
    @foreach (var item in Model)
    {
        <div>
            <input type="radio" name="id" id="id" value="@item.SiteDataId" />
            <label for="phase1">@item.SiteData_Name</label>
        </div>
    }
    <input type="submit" name="save" value="save" />

</form>

Areas/Admin/Views/SiteData/Edit.cshtml
@model Prototype.Models.SiteData

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}
<h1>Edit for @Model.SiteData_Name</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SiteDataId" />
            <div class="form-group">
                <label asp-for="SiteData_Link" class="control-label">Website Link</label>
                <input  asp-for="SiteData_Link" class="form-control" style="min-width:100%" />
                <span asp-validation-for="SiteData_Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiteData_Name" class="control-label">@Model.SiteData_Name</label>
                <input asp-for="SiteData_Name" class="form-control" style="min-width:100%"/>
                <span asp-validation-for="SiteData_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/SiteData/Index.cshtml
@using Prototype.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model IEnumerable<Prototype.Models.SiteData>
@{ 
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}




@foreach (var active in Model)
{
    @if (active.SiteData_Active == true)
    {
        @await Html.PartialAsync("_ActivePage", active)
    }
}

<div>
    @foreach (var item in Model)
    {
        <div>
            <a asp-controller="SiteData" asp-action="Edit" asp-route-id="@item.SiteDataId" class=" btn btn-danger"> @Html.DisplayFor(modelItem => item.SiteData_Name)</a>
        </div>
    }
</div>

Areas/Admin/Views/SiteData/_ActivePage.cshtml
@model Prototype.Models.SiteData



    <h3>Current Active Phase is @Model.SiteData_Name .</h3>

Areas/Admin/Views/SiteData/_Layout.cshtml
@using System.Web.Mvc;
@{ 
    ViewData["Title"] = "_Layout";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    
}

<h1>Site Index</h1>
<div>

    
</div>
<div>
    @RenderBody()
</div>